import './style.css';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { feature } from 'topojson-client';
import { createClient } from '@supabase/supabase-js';

const C={sky:'#6AC6E8',yellow:'#FFD764',orange:'#FF884D',cream:'#F7F7F7',ink:'#232323',blue:'#397FCE',teal:'#54C7C4'};
const url=import.meta.env.VITE_SUPABASE_URL||''; const key=import.meta.env.VITE_SUPABASE_ANON_KEY||'';
const supabase=url&&key?createClient(url,key):null;
const demo=[
['Marco','Bianchi','Porto','Portugal',41.1579,-8.6291,'Faith. Waves. People.','@marcobianchi',C.yellow],
['Sofia','Martin','Bali','Indonesia',-8.4095,115.1889,'Find your people.','@sofiawaves',C.teal],
['Luca','Rossi','Lisbon','Portugal',38.7223,-9.1393,'Saltwater fixes everything.','@lucarossi',C.orange],
['Tommaso','Verdi','Ericeira','Portugal',38.9637,-9.4173,'Stay curious.','@tomverdi',C.blue],
['Emily','Johnson','Taghazout','Morocco',30.5428,-9.7112,'Good waves, good people.','@emilywaves',C.teal],
['Jack','Wilson','Byron Bay','Australia',-28.6474,153.602,"Let's go.",'@jackwilson',C.yellow],
['Chloe','Dubois','Hossegor','France',43.662,-1.428,'Adventure is better together.','@chloedubois',C.orange]
].map((x,i)=>({id:String(i+1),first_name:x[0],last_name:x[1],city:x[2],country:x[3],lat:x[4],lon:x[5],quote:x[6],instagram:x[7],color:x[8]}));

const root=document.querySelector('#root');
root.innerHTML='<div id="app"><div class="brand-block"><div class="logo">SURF<br>CHURCH</div><div class="world">WORLD</div><div class="scribble">EXPLORE<br>YOUR PEOPLE</div></div><header class="top"><div class="find-title">FIND YOUR PEOPLE</div><div class="search"><span>⌕</span><input id="search" placeholder="Search by name..."></div><button id="add" class="add">📍 ADD YOUR PIN</button><div class="join-note">Join the map! ↘</div></header><main class="map-frame"><div id="map"></div><div class="map-caption">SURF CHURCH WORLD<small>DRAG · EXPLORE · FIND YOUR PEOPLE</small></div><div class="hq-caption">SURF CHURCH PORTO<small>MATOSINHOS · OUR HOME BASE</small></div></main><aside class="friends"><div class="friends-head">FRIENDS ON THE MAP</div><div id="friendList"></div></aside><div class="stickers"><b class="good">GOOD<br>VIBES</b><b class="smile">☺</b><b class="shaka">🤙</b><b class="faith">FAITH.<br>WAVES.<br>PEOPLE.</b><b class="jesus">✚ JESUS<br>OVER<br>EVERYTHING</b></div><div class="hint">SEARCH · EXPLORE · ADD YOUR PIN</div><section id="profile" class="profile"><button id="closeProfile" class="x">×</button><div class="profile-row"><div id="avatar" class="avatar-big"></div><div><h2 id="pname"></h2><p id="pquote"></p></div></div><div id="pinfo"></div><b class="tag">SURF CAMP COMMUNITY</b></section><div id="modal" class="modal-wrap"><div class="modal"><button id="closeModal" class="x">×</button><h2>JOIN THE MAP!</h2><p>Add yourself to the world. No password.</p><label>FIRST NAME<input id="first" placeholder="Federico"></label><label>LAST NAME<input id="last" placeholder="Nigro"></label><label>CITY / COUNTRY<input id="place" placeholder="Matosinhos, Portugal"></label><label>INSTAGRAM<input id="ig" placeholder="@yourhandle"></label><label>YOUR QUOTE<input id="quote" placeholder="Faith. Waves. People."></label><div class="actions"><button id="cancel">CANCEL</button><button id="save" class="save">DROP MY PIN</button></div></div></div><div id="toast"></div></div>';

const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(32,1,.1,100);camera.position.set(0,.05,4.3);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;document.querySelector('#map').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=true;controls.dampingFactor=.06;controls.rotateSpeed=.42;controls.zoomSpeed=.5;controls.minDistance=2.6;controls.maxDistance=5.5;
scene.add(new THREE.HemisphereLight(0xdff8ff,0x29465c,1.8));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(4,5,6);scene.add(sun);
const world=new THREE.Group();scene.add(world);const R=1.55;
const globe=new THREE.Mesh(new THREE.SphereGeometry(R,96,64),new THREE.MeshStandardMaterial({color:0x397fce,roughness:1}));world.add(globe);
world.add(new THREE.Mesh(new THREE.SphereGeometry(R*1.035,64,48),new THREE.MeshBasicMaterial({color:0xb8f2ff,transparent:true,opacity:.12,side:THREE.BackSide})));
function pos(lat,lon,r=R+.025){const p=(90-lat)*Math.PI/180,t=(lon+180)*Math.PI/180;return new THREE.Vector3(-r*Math.sin(p)*Math.cos(t),r*Math.cos(p),r*Math.sin(p)*Math.sin(t));}
function textSprite(text,sub){const c=document.createElement('canvas');c.width=700;c.height=180;const g=c.getContext('2d');g.textAlign='center';g.font='900 42px Arial';g.lineWidth=12;g.strokeStyle=C.ink;g.fillStyle=C.cream;g.strokeText(text,350,70);g.fillText(text,350,70);if(sub){g.font='700 22px Arial';g.strokeText(sub,350,118);g.fillText(sub,350,118)}const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.scale.set(.78,.2,1);return s;}
function pin(p,hq=false){const g=new THREE.Group();g.position.copy(pos(p.lat,p.lon,R+.06));g.lookAt(g.position.clone().multiplyScalar(2));const ball=new THREE.Mesh(new THREE.SphereGeometry(hq?.105:.075,20,16),new THREE.MeshStandardMaterial({color:new THREE.Color(hq?C.orange:p.color),roughness:.8}));ball.position.y=.18;g.add(ball);const ring=new THREE.Mesh(new THREE.TorusGeometry(hq?.135:.095,.014,8,24),new THREE.MeshBasicMaterial({color:C.cream}));ring.position.y=.18;g.add(ring);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,.18,8),new THREE.MeshBasicMaterial({color:C.ink}));stem.position.y=.07;g.add(stem);const label=textSprite(hq?'SURF CHURCH PORTO':'●',hq?'MATOSINHOS':'');label.position.y=hq?.52:.38;label.scale.set(hq?1.05:.45,hq?.27:.16,1);g.add(label);g.userData.profile=p;return g;}
const hq={name:'Surf Church Porto',city:'Matosinhos, Porto',lat:41.2269,lon:-8.7053,quote:'Faith. Waves. People.',instagram:'@surfchurchporto',color:C.orange};
const hqPin=pin(hq,true);world.add(hqPin);
const island=new THREE.Mesh(new THREE.CylinderGeometry(.27,.34,.08,8),new THREE.MeshStandardMaterial({color:0x6fbf73,roughness:1}));island.position.y=-.06;hqPin.add(island);const house=new THREE.Mesh(new THREE.BoxGeometry(.24,.15,.18),new THREE.MeshStandardMaterial({color:0x776b5f,roughness:1}));house.position.y=.06;hqPin.add(house);const roof=new THREE.Mesh(new THREE.ConeGeometry(.19,.13,4),new THREE.MeshStandardMaterial({color:C.ink}));roof.rotation.y=Math.PI/4;roof.position.y=.2;hqPin.add(roof);
for(let i=0;i<3;i++){const b=new THREE.Mesh(new THREE.CapsuleGeometry(.022,.12,4,8),new THREE.MeshStandardMaterial({color:[C.yellow,C.orange,C.blue][i]}));b.rotation.z=Math.PI/2;b.position.set(-.13+i*.06,.12,.1);hqPin.add(b)}
const pins=demo.map(p=>{const g=pin(p);world.add(g);return g});
function countries(){const c=document.createElement('canvas');c.width=2048;c.height=1024;const x=c.getContext('2d');x.fillStyle=C.blue;x.fillRect(0,0,c.width,c.height);for(let y=0;y<c.height;y+=72){x.strokeStyle='rgba(255,255,255,.13)';x.lineWidth=3;for(let a=-40;a<2100;a+=120){x.beginPath();x.arc(a,y,24,Math.PI,Math.PI*2);x.stroke()}}fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json').then(r=>r.json()).then(t=>{const geo=feature(t,t.objects.countries);const pal=['#F0D28B','#6FBF73','#FFD764','#54C7C4','#FF884D','#8D79C9','#72CBE9'];geo.features.forEach((f,i)=>{const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;polys.forEach(poly=>poly.forEach(ring=>{x.beginPath();ring.forEach(([lon,lat],j)=>{const X=(lon+180)/360*c.width,Y=(90-lat)/180*c.height;j?x.lineTo(X,Y):x.moveTo(X,Y)});x.closePath();x.fillStyle=pal[i%pal.length];x.fill();x.strokeStyle=C.ink;x.lineWidth=3;x.stroke()}))});globe.material.map=new THREE.CanvasTexture(c);globe.material.needsUpdate=true}).catch(()=>{});}countries();
function show(p){document.querySelector('#profile').classList.add('active');document.querySelector('#pname').textContent=p.name||p.first_name+' '+p.last_name;document.querySelector('#pquote').textContent='“'+(p.quote||'')+'”';document.querySelector('#pinfo').innerHTML='📍 '+(p.city||'')+(p.country?', '+p.country:'')+'<br>◎ '+(p.instagram||'');document.querySelector('#avatar').textContent=(p.first_name||p.name||'?').slice(0,1)}
const list=document.querySelector('#friendList');function render(arr){list.innerHTML='';arr.forEach(p=>{const d=document.createElement('div');d.className='friend';d.innerHTML='<div class="av">'+p.first_name[0]+p.last_name[0]+'</div><div class="meta"><b>'+p.first_name+' '+p.last_name+'</b><small>'+p.city+', '+p.country+'</small></div><i class="dot" style="background:'+p.color+'"></i>';d.onclick=()=>{show(p);camera.position.copy(pos(p.lat,p.lon,3.5));controls.target.set(0,0,0)};list.appendChild(d)})}render(demo);
document.querySelector('#search').oninput=e=>{const q=e.target.value.toLowerCase();render(demo.filter(p=>(p.first_name+' '+p.last_name).toLowerCase().includes(q)))};
const modal=document.querySelector('#modal');document.querySelector('#add').onclick=()=>modal.classList.add('show');document.querySelector('#closeModal').onclick=()=>modal.classList.remove('show');document.querySelector('#cancel').onclick=()=>modal.classList.remove('show');document.querySelector('#closeProfile').onclick=()=>document.querySelector('#profile').classList.remove('active');
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
document.querySelector('#save').onclick=async()=>{const first=document.querySelector('#first').value.trim(),last=document.querySelector('#last').value.trim(),place=document.querySelector('#place').value.trim(),ig=document.querySelector('#ig').value.trim(),quote=document.querySelector('#quote').value.trim();if(!first||!last||!place)return toast('Add your name and location ✌');const parts=place.split(',').map(s=>s.trim());const p={first_name:first,last_name:last,city:parts[0],country:parts[1]||'',lat:41.2269,lon:-8.7053,quote:quote||'Faith. Waves. People.',instagram:ig||'@surfer',color:C.yellow};if(supabase){const {error}=await supabase.from('profiles').insert(p);if(error)return toast('Could not save your pin')}world.add(pin(p));show(p);modal.classList.remove('show');toast('You are on the map! 🌍')};
async function load(){if(!supabase)return;const {data}=await supabase.from('profiles').select('*').order('created_at',{ascending:true});if(data)data.forEach(p=>world.add(pin(p)))}load();
function resize(){const el=document.querySelector('#map');camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)}addEventListener('resize',resize);resize();
function animate(t){requestAnimationFrame(animate);controls.update();pins.forEach((p,i)=>{p.children[0].position.y=.18+Math.sin(t*.002+i)*.025;p.children[1].position.y=.18+Math.sin(t*.002+i)*.025});renderer.render(scene,camera)}animate(0);
