import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { feature } from 'topojson-client';
import { createClient } from '@supabase/supabase-js';

const C={sky:'#6AC6E8',yellow:'#FFD764',orange:'#FF884D',cream:'#F7F7F7',ink:'#232323',blue:'#397FCE',teal:'#54C7C4'};
const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'';
const SUPABASE_ANON_KEY=import.meta.env.VITE_SUPABASE_ANON_KEY||'';
const supabase=SUPABASE_URL&&SUPABASE_ANON_KEY?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const demo=[
{id:'1',first_name:'Marco',last_name:'Bianchi',city:'Porto',country:'Portugal',lat:41.1579,lon:-8.6291,quote:'Faith. Waves. People.',instagram:'@marcobianchi',color:C.yellow},
{id:'2',first_name:'Sofia',last_name:'Martin',city:'Bali',country:'Indonesia',lat:-8.4095,lon:115.1889,quote:'Find your people.',instagram:'@sofiawaves',color:C.teal},
{id:'3',first_name:'Luca',last_name:'Rossi',city:'Lisbon',country:'Portugal',lat:38.7223,lon:-9.1393,quote:'Saltwater fixes everything.',instagram:'@lucarossi',color:C.orange},
{id:'4',first_name:'Tommaso',last_name:'Verdi',city:'Ericeira',country:'Portugal',lat:38.9637,lon:-9.4173,quote:'Stay curious.',instagram:'@tomverdi',color:C.blue},
{id:'5',first_name:'Emily',last_name:'Johnson',city:'Taghazout',country:'Morocco',lat:30.5428,lon:-9.7112,quote:'Good waves, good people.',instagram:'@emilywaves',color:C.teal},
{id:'6',first_name:'Jack',last_name:'Wilson',city:'Byron Bay',country:'Australia',lat:-28.6474,lon:153.602,quote:'Let\'s go.',instagram:'@jackwilson',color:C.yellow},
{id:'7',first_name:'Chloe',last_name:'Dubois',city:'Hossegor',country:'France',lat:43.662,lon:-1.428,quote:'Adventure is better together.',instagram:'@chloedubois',color:C.orange}
];

const root=document.querySelector('#root');
root.innerHTML=`<div id="app">
<div class="paper-strip left-brand"><div class="logo">SURF<br>CHURCH</div><div class="world">WORLD</div><div class="scribble">EXPLORE<br>YOUR PEOPLE</div></div>
<header class="yellow-panel"><div class="section-title">FIND YOUR PEOPLE</div><div class="search"><span>⌕</span><input id="search" placeholder="Search by name..."/></div><button id="add" class="pin-btn">📍 &nbsp; ADD YOUR PIN</button><div class="join-note">Join the map! ↘</div></header>
<main class="map-frame"><div id="map"></div><div class="map-caption">SURF CHURCH WORLD <small>DRAG · EXPLORE · FIND YOUR PEOPLE</small></div><div class="hq-caption">SURF CHURCH PORTO<small>MATOSINHOS · OUR HOME BASE</small></div></main>
<aside class="friends paper"><div class="friends-head">FRIENDS ON THE MAP</div><div id="friendList"></div></aside>
<div class="bottom-stickers"><span class="sticker good">GOOD<br>VIBES</span><span class="sticker smile">☺</span><span class="sticker shaka">🤙</span><span class="sticker faith">FAITH.<br>WAVES.<br>PEOPLE.</span><span class="sticker jesus">✚ JESUS<br>OVER<br>EVERYTHING</span></div>
<div class="hint">SEARCH · EXPLORE · ADD YOUR PIN</div>
<section id="profile" class="profile paper"><button id="closeProfile" class="x">×</button><div class="profile-main"><div id="profileAvatar" class="avatar-big"></div><div><h2 id="profileName"></h2><p id="profileQuote"></p></div></div><div id="profileInfo"></div><b class="tag">SURF CAMP COMMUNITY</b></section>
<div id="modal" class="modal-wrap"><div class="modal paper"><button id="closeModal" class="x">×</button><h2>JOIN THE MAP!</h2><p>Add yourself to the world. No password.</p><label>FIRST NAME<input id="first" placeholder="Federico"></label><label>LAST NAME<input id="last" placeholder="Nigro"></label><label>CITY / COUNTRY<input id="place" placeholder="Matosinhos, Portugal"></label><label>INSTAGRAM<input id="ig" placeholder="@yourhandle"></label><label>YOUR QUOTE<input id="quote" placeholder="Faith. Waves. People."></label><div class="actions"><button id="cancel">CANCEL</button><button id="save" class="save">DROP MY PIN</button></div></div></div><div id="toast"></div></div>`;

const style=document.createElement('style');style.textContent=`
@import url('https://fonts.googleapis.com/css2?family=Anton&family=Permanent+Marker&display=swap');
:root{--sky:${C.sky};--yellow:${C.yellow};--orange:${C.orange};--cream:${C.cream};--ink:${C.ink};--blue:${C.blue};--teal:${C.teal}}
*{box-sizing:border-box}html,body,#root,#app{margin:0;width:100%;height:100%;overflow:hidden}body{background:#e9e4d8;color:var(--ink);font-family:Arial,sans-serif}.paper{background:var(--cream);border:3px solid var(--ink);box-shadow:7px 7px 0 var(--ink);border-radius:16px}
#app{position:relative;min-height:100vh;background:repeating-linear-gradient(0deg,rgba(35,35,35,.025) 0 1px,transparent 1px 4px),#eee9dd}.left-brand{position:absolute;z-index:20;left:0;top:0;width:270px;height:155px;background:var(--sky);padding:19px 30px;border-right:4px solid var(--ink);border-bottom:4px solid var(--ink)}.logo{font-family:Anton,Impact,sans-serif;font-style:italic;color:var(--cream);font-size:42px;line-height:.77;letter-spacing:-2px;text-shadow:3px 3px 0 var(--ink),-2px -2px 0 var(--ink),2px -2px 0 var(--ink),-2px 2px 0 var(--ink);transform:rotate(-2deg)}.world{font-family:Anton,sans-serif;color:var(--orange);font-size:27px;margin-left:104px;text-shadow:2px 2px 0 var(--ink);margin-top:4px}.scribble{font-family:'Permanent Marker',cursive;position:absolute;right:-35px;top:112px;transform:rotate(-7deg);font-size:12px;line-height:1.05}
.yellow-panel{position:absolute;z-index:19;left:270px;right:320px;top:0;height:155px;background:var(--yellow);border-bottom:4px solid var(--ink);padding:25px 34px}.section-title{font-family:Anton,Impact,sans-serif;font-size:31px;letter-spacing:.5px}.search{margin-top:10px;width:350px;height:43px;background:var(--cream);border:3px solid var(--ink);border-radius:10px;box-shadow:4px 4px 0 var(--ink);display:flex;align-items:center;padding:0 12px}.search span{font-size:22px;margin-right:8px}.search input{border:0;outline:0;background:transparent;width:100%;font-size:15px;font-weight:700}.pin-btn{position:absolute;right:35px;bottom:25px;background:var(--blue);color:#fff;border:3px solid var(--ink);border-radius:12px;box-shadow:5px 5px 0 var(--ink);height:49px;padding:0 25px;font-family:Anton,Impact,sans-serif;font-size:19px}.pin-btn:hover{transform:translate(2px,2px);box-shadow:3px 3px 0 var(--ink)}.join-note{position:absolute;right:55px;top:12px;font:18px 'Permanent Marker',cursive;transform:rotate(-5deg)}
.friends{position:absolute;z-index:21;right:0;top:0;width:320px;height:100%;border-radius:0;border-width:0 0 0 4px;box-shadow:none;overflow:auto}.friends-head{height:70px;background:var(--sky);color:var(--cream);font-family:Anton,Impact,sans-serif;font-size:24px;padding:20px 20px;border-bottom:3px solid var(--ink)}.friend{display:flex;align-items:center;gap:10px;padding:13px 17px;border-bottom:2px solid #bdb8ae;background:rgba(247,247,247,.9);cursor:pointer}.friend:hover{background:#fff0b0;transform:translateX(-3px)}.friend .av{width:52px;height:52px;border:3px solid var(--ink);border-radius:50%;background:var(--sky);display:grid;place-items:center;color:white;font-weight:900;font-size:17px;flex:none}.friend-meta{flex:1}.friend-meta b{font-size:15px}.friend-meta small{display:block;font-size:12px;margin-top:3px}.dot{width:14px;height:14px;border:2px solid var(--ink);border-radius:50%;flex:none}
.map-frame{position:absolute;left:285px;right:335px;top:175px;bottom:75px;border:4px solid var(--ink);box-shadow:9px 9px 0 var(--ink);border-radius:18px;overflow:hidden;background:var(--sky)}#map{position:absolute;inset:0;background:var(--sky)}#map canvas{display:block;width:100%;height:100%}.map-frame:after{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(135deg,rgba(255,255,255,.08),transparent 35%,rgba(35,35,35,.08));mix-blend-mode:overlay}.map-caption{position:absolute;z-index:5;left:20px;bottom:18px;background:var(--ink);color:var(--cream);padding:10px 14px;border-radius:9px;font-family:Anton,sans-serif;font-size:18px;box-shadow:4px 4px 0 rgba(255,255,255,.55)}.map-caption small{display:block;color:var(--yellow);font:700 10px Arial,sans-serif;margin-top:3px}.hq-caption{position:absolute;z-index:5;left:31%;bottom:11%;background:var(--ink);color:white;padding:9px 13px;border-radius:8px;font-family:Anton,sans-serif;font-size:16px;box-shadow:4px 4px 0 var(--yellow)}.hq-caption small{display:block;color:var(--yellow);font:700 9px Arial,sans-serif;margin-top:2px}
.bottom-stickers{position:absolute;z-index:30;left:24px;bottom:18px;display:flex;gap:10px;align-items:flex-end}.sticker{border:3px solid var(--ink);box-shadow:4px 4px 0 var(--ink);font-weight:1000;text-align:center;line-height:.82}.good{background:var(--cream);color:var(--orange);padding:10px;font:24px Anton,sans-serif;transform:rotate(-5deg);border-radius:12px;text-shadow:1px 1px 0 var(--ink)}.smile{background:var(--yellow);border-radius:50%;width:49px;height:49px;display:grid;place-items:center;font-size:31px;transform:rotate(7deg)}.shaka{background:var(--blue);padding:5px 9px;border-radius:12px;font-size:30px;transform:rotate(-7deg)}.faith{background:var(--yellow);border-radius:50%;padding:11px 15px;font:13px Anton,sans-serif;transform:rotate(4deg)}.jesus{background:var(--ink);color:var(--cream);border-radius:8px;padding:8px 12px;font:12px Anton,sans-serif;transform:rotate(-4deg)}.hint{position:absolute;z-index:10;left:50%;bottom:18px;transform:translateX(-50%);font:11px Anton,sans-serif;background:var(--cream);border:3px solid var(--ink);box-shadow:4px 4px 0 var(--ink);padding:8px 13px;border-radius:9px}
.profile{position:absolute;z-index:40;left:300px;bottom:90px;width:360px;padding:17px;display:none}.profile.active{display:block}.x{position:absolute;right:8px;top:5px;border:0;background:transparent;font-size:26px;font-weight:900}.profile-main{display:flex;gap:12px;align-items:center}.avatar-big{width:70px;height:70px;border:3px solid var(--ink);border-radius:50%;background:linear-gradient(135deg,var(--sky),var(--orange));display:grid;place-items:center;color:#fff;font-size:20px;font-weight:900}.profile h2{font:25px Anton,sans-serif;margin:0}.profile p{font:italic 700 13px Arial,sans-serif;margin:3px 0}.profile-info{font:700 13px Arial,sans-serif;line-height:1.7;margin-top:10px}.tag{display:inline-block;background:var(--teal);border:2px solid var(--ink);border-radius:7px;padding:4px 8px;font:11px Anton,sans-serif;margin-top:8px}.modal-wrap{position:absolute;inset:0;z-index:50;background:rgba(35,35,35,.55);display:none;align-items:center;justify-content:center}.modal-wrap.show{display:flex}.modal{width:min(470px,calc(100% - 30px));padding:22px;position:relative}.modal h2{font:31px Anton,sans-serif;margin:0}.modal p{font:700 13px Arial,sans-serif;color:#555}.modal label{font:10px Anton,sans-serif;display:block;margin:9px 0}.modal input{display:block;width:100%;border:3px solid var(--ink);border-radius:8px;padding:9px;margin-top:4px;background:white;outline:0;font:700 14px Arial,sans-serif}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:15px}.actions button{border:3px solid var(--ink);border-radius:8px;padding:9px 14px;background:#fff;font-weight:900}.actions .save{background:var(--orange);color:white}#toast{position:absolute;z-index:60;top:170px;left:50%;transform:translateX(-50%);background:var(--yellow);border:3px solid var(--ink);box-shadow:4px 4px 0 var(--ink);padding:9px 13px;border-radius:9px;font-weight:900;opacity:0;transition:.2s}#toast.show{opacity:1}
@media(max-width:950px){.left-brand{width:190px}.logo{font-size:31px}.world{font-size:21px;margin-left:70px}.yellow-panel{left:190px;right:240px;padding:17px 20px}.section-title{font-size:22px}.search{width:240px}.pin-btn{right:18px;font-size:14px;padding:0 13px}.friends{width:240px}.map-frame{left:15px;right:255px;top:170px;bottom:70px}.bottom-stickers{display:none}.profile{left:20px;bottom:70px}.join-note{display:none}}@media(max-width:700px){.left-brand{height:105px;width:145px;padding:12px}.logo{font-size:24px}.world{font-size:17px;margin-left:50px}.yellow-panel{left:145px;right:0;height:105px;padding:12px}.section-title{font-size:17px}.search{margin-top:6px;width:180px;height:34px}.pin-btn{bottom:12px;right:10px;height:36px;font-size:12px}.friends{top:115px;width:230px;height:43%}.map-frame{left:10px;right:10px;top:125px;bottom:75px}.hint{display:none}.profile{left:10px;bottom:10px;width:calc(100% - 20px)}}`;
document.head.appendChild(style);

const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(32,1,.1,100);camera.position.set(0,.05,4.25);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;document.querySelector('#map').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=true;controls.dampingFactor=.06;controls.rotateSpeed=.42;controls.zoomSpeed=.5;controls.minDistance=2.65;controls.maxDistance=5.5;
scene.add(new THREE.HemisphereLight(0xd9f8ff,0x31506a,1.8));const light=new THREE.DirectionalLight(0xffffff,2.4);light.position.set(4,5,6);scene.add(light);
const world=new THREE.Group();scene.add(world);const globeR=1.55;const globe=new THREE.Mesh(new THREE.SphereGeometry(globeR,96,64),new THREE.MeshStandardMaterial({color:0x397fce,roughness:1}));world.add(globe);
const glow=new THREE.Mesh(new THREE.SphereGeometry(globeR*1.035,64,48),new THREE.MeshBasicMaterial({color:0xb8f2ff,transparent:true,opacity:.11,side:THREE.BackSide}));world.add(glow);

function latLon(lat,lon,r=globeR+.018){const p=(90-lat)*Math.PI/180,t=(lon+180)*Math.PI/180;return new THREE.Vector3(-r*Math.sin(p)*Math.cos(t),r*Math.cos(p),r*Math.sin(p)*Math.sin(t));}
function labelSprite(text,color=C.cream,sub=''){const cv=document.createElement('canvas');cv.width=512;cv.height=160;const x=cv.getContext('2d');x.clearRect(0,0,512,160);x.font='900 36px Arial';x.textAlign='center';x.fillStyle=color;x.strokeStyle=C.ink;x.lineWidth=10;x.strokeText(text,256,62);x.fillText(text,256,62);if(sub){x.font='700 20px Arial';x.strokeText(sub,256,105);x.fillText(sub,256,105)}const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cv),transparent:true,depthTest:false}));s.scale.set(.7,.22,1);return s;}
function makePin(p,isHQ=false){const g=new THREE.Group();const pos=latLon(p.lat,p.lon,globeR+.055);g.position.copy(pos);g.lookAt(pos.clone().multiplyScalar(2));const stem=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,.16,8),new THREE.MeshBasicMaterial({color:C.ink}));stem.position.y=.07;g.add(stem);const pin=new THREE.Mesh(new THREE.SphereGeometry(isHQ?.09:.075,20,20),new THREE.MeshStandardMaterial({color:new THREE.Color(isHQ?C.orange:p.color),roughness:.8}));pin.position.y=.16;g.add(pin);const ring=new THREE.Mesh(new THREE.TorusGeometry(isHQ?.12:.095,.012,8,24),new THREE.MeshBasicMaterial({color:C.cream}));ring.position.y=.16;g.add(ring);const lab=labelSprite(isHQ?'HQ':'●',C.cream);lab.position.set(0,.34,0);g.add(lab);g.userData.profile=p;return g;}

function makeHQ(){const g=makePin({lat:41.2269,lon:-8.7053,color:C.orange,name:'Surf Church Porto',city:'Matosinhos, Porto',quote:'Faith. Waves. People.',instagram:'@surfchurchporto'},true);const island=new THREE.Mesh(new THREE.CylinderGeometry(.25,.31,.08,7),new THREE.MeshStandardMaterial({color:0x7dbb67,roughness:1}));island.position.y=-.05;g.add(island);const house=new THREE.Mesh(new THREE.BoxGeometry(.24,.16,.18),new THREE.MeshStandardMaterial({color:0x6b6258,roughness:1}));house.position.y=.05;g.add(house);const roof=new THREE.Mesh(new THREE.ConeGeometry(.19,.13,4),new THREE.MeshStandardMaterial({color:C.ink,roughness:1}));roof.rotation.y=Math.PI/4;roof.position.y=.19;g.add(roof);for(let i=0;i<3;i++){const board=new THREE.Mesh(new THREE.CapsuleGeometry(.025,.12,4,8),new THREE.MeshStandardMaterial({color:[C.yellow,C.orange,C.blue][i]}));board.rotation.z=Math.PI/2;board.rotation.y=.2;board.position.set(-.16+i*.055,.11,.1);g.add(board)}const lab=labelSprite('SURF CHURCH PORTO',C.cream,'MATOSINHOS');lab.scale.set(.9,.28,1);lab.position.set(0,.48,0);g.add(lab);return g;}
world.add(makeHQ());
const pins=demo.map(p=>{const g=makePin(p);world.add(g);return g});

function drawWorldTexture(){const cv=document.createElement('canvas');cv.width=2048;cv.height=1024;const ctx=cv.getContext('2d');ctx.fillStyle=C.blue;ctx.fillRect(0,0,2048,1024);for(let y=0;y<1024;y+=80){ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=3;for(let x=-50;x<2100;x+=130){ctx.beginPath();ctx.arc(x,y,25,Math.PI,Math.PI*2);ctx.stroke()}}fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json').then(r=>r.json()).then(topo=>{const geo=feature(topo,topo.objects.countries);const pal=['#F0D28B','#6FBF73','#FFD764','#54C7C4','#FF884D','#8D79C9','#72CBE9'];geo.features.forEach((f,i)=>{const col=pal[i%pal.length];ctx.beginPath();const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;polys.forEach(poly=>poly.forEach((ring,ri)=>{ring.forEach(([lon,lat],j)=>{const X=(lon+180)/360*2048,Y=(90-lat)/180*1024;j?ctx.lineTo(X,Y):ctx.moveTo(X,Y)});ctx.closePath()}));ctx.fillStyle=col;ctx.fill();ctx.strokeStyle=C.ink;ctx.lineWidth=3;ctx.stroke()});globe.material.map=new THREE.CanvasTexture(cv);globe.material.needsUpdate=true}).catch(()=>{});}
drawWorldTexture();

const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('click',e=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(world.children,true).find(h=>h.object.parent?.userData?.profile||h.object.userData?.profile);if(!hit)return;let o=hit.object;while(o.parent&& !o.userData.profile)o=o.parent;const p=o.userData.profile;if(p)showProfile(p)});
function showProfile(p){document.querySelector('#profile').classList.add('active');document.querySelector('#profileName').textContent=`${p.first_name||p.name} ${p.last_name||''}`;document.querySelector('#profileQuote').textContent=`“${p.quote||''}”`;document.querySelector('#profileInfo').innerHTML=`📍 ${p.city||''}, ${p.country||''}<br>◎ ${p.instagram||''}`;document.querySelector('#profileAvatar').textContent=(p.first_name||p.name||'?').slice(0,1)}
document.querySelector('#closeProfile').onclick=()=>document.querySelector('#profile').classList.remove('active');
const list=document.querySelector('#friendList');function render(items=demo){list.innerHTML=items.map(p=>`<div class="friend" data-id="${p.id}"><div class="av">${p.first_name[0]}${p.last_name[0]}</div><div class="friend-meta"><b>${p.first_name} ${p.last_name}</b><small>${p.city}, ${p.country}</small></div><i class="dot" style="background:${p.color}"></i></div>`).join('');list.querySelectorAll('.friend').forEach(el=>el.onclick=()=>{const p=demo.find(x=>x.id===el.dataset.id);showProfile(p);focusPin(p)});}render();
function focusPin(p){const target=latLon(p.lat,p.lon,3.4);camera.position.copy(target);controls.target.set(0,0,0)}
document.querySelector('#search').oninput=e=>{const q=e.target.value.toLowerCase();render(demo.filter(p=>`${p.first_name} ${p.last_name}`.toLowerCase().includes(q)))};
const modal=document.querySelector('#modal');document.querySelector('#add').onclick=()=>modal.classList.add('show');document.querySelector('#closeModal').onclick=()=>modal.classList.remove('show');document.querySelector('#cancel').onclick=()=>modal.classList.remove('show');
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
document.querySelector('#save').onclick=async()=>{const first=document.querySelector('#first').value.trim(),last=document.querySelector('#last').value.trim(),place=document.querySelector('#place').value.trim(),ig=document.querySelector('#ig').value.trim(),quote=document.querySelector('#quote').value.trim();if(!first||!last||!place)return toast('Add your name and location ✌');const parts=place.split(',').map(x=>x.trim());const p={id:'me',first_name:first,last_name:last,city:parts[0]||place,country:parts[1]||'',lat:41.2269,lon:-8.7053,quote:quote||'Faith. Waves. People.',instagram:ig||'@surfer',color:C.yellow};if(supabase){const {error}=await supabase.from('profiles').insert({first_name:first,last_name:last,city:p.city,country:p.country,lat:p.lat,lon:p.lon,quote:p.quote,instagram:p.instagram});if(error)return toast('Could not save your pin');}world.add(makePin(p));showProfile(p);modal.classList.remove('show');toast('You are on the map! 🌍')};
async function loadProfiles(){if(!supabase)return;const {data}=await supabase.from('profiles').select('*').order('created_at',{ascending:true});if(!data)return;data.forEach(p=>{if(!demo.some(d=>d.id===p.id))world.add(makePin(p))})}loadProfiles();
function resize(){const el=document.querySelector('#map');camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)}addEventListener('resize',resize);resize();
function animate(t){requestAnimationFrame(animate);controls.update();pins.forEach((p,i)=>{p.position.y+=Math.sin(t*.002+i)*.00003});renderer.render(scene,camera)}animate(0);`;
