import './style.css';
import * as BABYLON from '@babylonjs/core';
import '@babylonjs/loaders';
import * as GUI from '@babylonjs/gui';
import { createClient } from '@supabase/supabase-js';

const C={sky:'#6AC6E8',yellow:'#FFD764',orange:'#FF884D',cream:'#FFF9EA',ink:'#232323',blue:'#397FCE',teal:'#54C7C4'};
const supabaseUrl=import.meta.env.VITE_SUPABASE_URL||'';
const supabaseKey=import.meta.env.VITE_SUPABASE_ANON_KEY||'';
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
const demo=[
['Marco','Bianchi','Porto','Portugal',41.1579,-8.6291,'Faith. Waves. People.','@marcobianchi',C.yellow,12],
['Sofia','Martin','Bali','Indonesia',-8.4095,115.1889,'Find your people.','@sofiawaves',C.teal,47],
['Luca','Rossi','Lisbon','Portugal',38.7223,-9.1393,'Saltwater fixes everything.','@lucarossi',C.orange,33],
['Tommaso','Verdi','Ericeira','Portugal',38.9637,-9.4173,'Stay curious.','@tomverdi',C.blue,11],
['Emily','Johnson','Taghazout','Morocco',30.5428,-9.7112,'Good waves, good people.','@emilywaves',C.teal,44],
['Jack','Wilson','Byron Bay','Australia',-28.6474,153.602,"Let's go.",'@jackwilson',C.yellow,59],
['Chloe','Dubois','Hossegor','France',43.662,-1.428,'Adventure is better together.','@chloedubois',C.orange,45]
].map((x,i)=>({id:String(i+1),first_name:x[0],last_name:x[1],city:x[2],country:x[3],lat:x[4],lon:x[5],quote:x[6],instagram:x[7],color:x[8],avatar_url:`https://i.pravatar.cc/160?img=${x[9]}`}));

const root=document.querySelector('#root');
root.innerHTML=`<div id="app"><div class="brand-block"><div class="logo">SURF<br>CHURCH</div><div class="world">WORLD</div><div class="scribble">EXPLORE<br>YOUR PEOPLE</div></div><header class="top"><div class="find-title">FIND YOUR PEOPLE</div><div class="search"><span>⌕</span><input id="search" placeholder="Search by name..."></div><button id="add" class="add">📍 ADD YOUR PIN</button><div class="join-note">Join the map! ↘</div></header><main class="map-frame"><div id="map"></div><div class="map-caption">SURF CHURCH WORLD<small>DRAG · EXPLORE · FIND YOUR PEOPLE</small></div></main><aside class="friends"><div class="friends-head">FRIENDS ON THE MAP</div><div id="friendList"></div></aside><div class="stickers"><b class="good">GOOD<br>VIBES</b><b class="smile">☺</b><b class="shaka">🤙</b><b class="faith">FAITH.<br>WAVES.<br>PEOPLE.</b><b class="jesus">✚ JESUS<br>OVER<br>EVERYTHING</b></div><div class="hint">SEARCH · EXPLORE · ADD YOUR PIN</div><section id="profile" class="profile"><button id="closeProfile" class="x">×</button><div class="profile-row"><img id="avatar" class="avatar-big" alt=""><div><h2 id="pname"></h2><p id="pquote"></p></div></div><div id="pinfo" class="profile-info"></div><b class="tag">SURF CAMP COMMUNITY</b></section><div id="modal" class="modal-wrap"><div class="modal"><button id="closeModal" class="x">×</button><h2>JOIN THE MAP!</h2><p>Add yourself to the world. No password.</p><label>FIRST NAME<input id="first" placeholder="Federico"></label><label>LAST NAME<input id="last" placeholder="Nigro"></label><label>CITY / COUNTRY<input id="place" placeholder="Matosinhos, Portugal"></label><label>INSTAGRAM<input id="ig" placeholder="@yourhandle"></label><label>YOUR QUOTE<input id="quote" placeholder="Faith. Waves. People."></label><div class="actions"><button id="cancel">CANCEL</button><button id="save" class="save">DROP MY PIN</button></div></div></div><div id="toast"></div></div>`;

const mapEl=document.querySelector('#map');
const canvas=document.createElement('canvas');canvas.style.width='100%';canvas.style.height='100%';mapEl.appendChild(canvas);
const engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true},true);
const scene=new BABYLON.Scene(engine);scene.clearColor=BABYLON.Color4.FromHexString(C.sky+'ff');
const camera=new BABYLON.ArcRotateCamera('player-camera',-1.15,1.18,4.2,BABYLON.Vector3.Zero(),scene);camera.attachControl(canvas,true);camera.lowerRadiusLimit=2.55;camera.upperRadiusLimit=5.4;camera.wheelPrecision=55;camera.panningSensibility=0;camera.inertia=.78;camera.angularSensibilityX=850;camera.angularSensibilityY=850;
const hemi=new BABYLON.HemisphericLight('sky-light',new BABYLON.Vector3(0,1,0),2.1);hemi.groundColor=BABYLON.Color3.FromHexString('#2C6070');
const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.4,-.8,-.6),3.2);sun.diffuse=BABYLON.Color3.FromHexString('#FFF4DD');
const world=new BABYLON.TransformNode('game-world',scene);const R=1.52;

function mat(name,color,rough=1){const m=new BABYLON.StandardMaterial(name,scene);m.diffuseColor=BABYLON.Color3.FromHexString(color);m.specularColor=new BABYLON.Color3(0,0,0);m.roughness=rough;return m}
const ocean=mat('arcade-ocean',C.blue);const earth=BABYLON.MeshBuilder.CreateSphere('WORLD',{diameter:R*2,segments:64},scene);earth.material=ocean;earth.parent=world;
const rimMat=new BABYLON.StandardMaterial('rim',scene);rimMat.diffuseColor=BABYLON.Color3.FromHexString('#D9F8FF');rimMat.alpha=.15;const rim=BABYLON.MeshBuilder.CreateSphere('atmosphere',{diameter:R*2.08,segments:48},scene);rim.material=rimMat;rim.parent=world;

function latLon(lat,lon,r=R+.025){const p=(90-lat)*Math.PI/180,t=(lon+180)*Math.PI/180;return new BABYLON.Vector3(-r*Math.sin(p)*Math.cos(t),r*Math.cos(p),r*Math.sin(p)*Math.sin(t))}
function orient(node,pos){node.position=pos;node.lookAt(BABYLON.Vector3.Zero())}

// World-art texture is generated as an actual game asset at runtime: bold countries, hand-drawn ocean waves and thick outlines.
async function paintCountries(){const c=document.createElement('canvas');c.width=2048;c.height=1024;const x=c.getContext('2d');x.fillStyle=C.blue;x.fillRect(0,0,c.width,c.height);x.strokeStyle='rgba(255,255,255,.25)';x.lineWidth=4;for(let y=35;y<c.height;y+=58){for(let xx=-40;xx<c.width+40;xx+=110){x.beginPath();x.arc(xx,y,24,Math.PI,Math.PI*2);x.stroke()}}
try{const r=await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json');const topo=await r.json();const obj=topo.objects.countries;const features=(await import('topojson-client')).feature(topo,obj).features;const pal=['#F2D39A','#6FBF73','#FFD764','#54C7C4','#FF884D','#8E7BC5','#72CBE9'];features.forEach((f,i)=>{const gs=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;gs.forEach(poly=>poly.forEach(ring=>{x.beginPath();ring.forEach(([lon,lat],j)=>{const X=(lon+180)/360*c.width,Y=(90-lat)/180*c.height;j?x.lineTo(X,Y):x.moveTo(X,Y)});x.closePath();x.fillStyle=pal[i%pal.length];x.fill();x.strokeStyle=C.ink;x.lineWidth=2.2;x.stroke()}))})}catch(e){console.warn('Country art unavailable',e)}
const tex=new BABYLON.DynamicTexture('painted-world',c,scene,false);tex.hasAlpha=false;tex.update();const m=mat('country-art',C.blue);m.diffuseTexture=tex;m.emissiveColor=new BABYLON.Color3(.05,.05,.05);earth.material=m}
paintCountries();

function addCloud(lat,lon,s=.09){const g=new BABYLON.TransformNode('cloud',scene);orient(g,latLon(lat,lon,R+.07));for(let i=0;i<3;i++){const q=BABYLON.MeshBuilder.CreateSphere('cloud-puff',{diameter:s*(i===1?1.3:1),segments:12},scene);q.material=mat('cloudmat','#FFFFFF');q.parent=g;q.position.x=(i-1)*s*.5}return g}
[[38,-25],[15,80],[-20,-90],[-34,50],[50,120]].forEach(v=>addCloud(v[0],v[1]));
function addBalloon(lat,lon,color){const g=new BABYLON.TransformNode('balloon',scene);orient(g,latLon(lat,lon,R+.13));const b=BABYLON.MeshBuilder.CreateSphere('balloon-body',{diameter:.13,segments:12},scene);b.scaling.y=1.3;b.position.y=.11;b.material=mat('balloonmat',color);b.parent=g;const basket=BABYLON.MeshBuilder.CreateBox('basket',{size:.035},scene);basket.position.y=-.01;basket.material=mat('basketmat',C.ink);basket.parent=g;return g}[[48,8,C.orange],[28,120,C.yellow],[-18,30,C.teal]].forEach(v=>addBalloon(...v));

function label(text,sub,color=C.cream){const g=new GUI.Rectangle();g.width='190px';g.height='54px';g.cornerRadius=10;g.thickness=3;g.color=C.ink;g.background=color;const t=new GUI.TextBlock();t.text=text+'\n'+(sub||'');t.color=C.ink;t.fontFamily='Anton';t.fontSize=17;t.fontWeight='900';g.addControl(t);return g}
const gui=GUI.AdvancedDynamicTexture.CreateFullscreenUI('game-ui');

function addHQ(){const p=latLon(41.2269,-8.7053,R+.04);const root=new BABYLON.TransformNode('SURF_CHURCH_PORTO',scene);orient(root,p);const island=BABYLON.MeshBuilder.CreateCylinder('hq-island',{height:.10,diameterTop:.58,diameterBottom:.68,tessellation:9},scene);island.material=mat('grass','#72B96D');island.parent=root;const house=BABYLON.MeshBuilder.CreateBox('surf-warehouse',{width:.30,height:.18,depth:.24},scene);house.position.y=.10;house.material=mat('warehouse','#8B7968');house.parent=root;const roof=BABYLON.MeshBuilder.CreateCylinder('roof',{height:.16,diameter:.48,tessellation:4},scene);roof.rotation.y=Math.PI/4;roof.position.y=.27;roof.material=mat('roof',C.ink);roof.parent=root;for(let i=0;i<3;i++){const board=BABYLON.MeshBuilder.CreateCapsule('surfboard',{height:.18,radius:.025},scene);board.rotation.z=Math.PI/2;board.position.set(-.13+i*.065,.13,.15);board.material=mat('board'+i,[C.yellow,C.orange,C.blue][i]);board.parent=root}for(let i=0;i<3;i++){const trunk=BABYLON.MeshBuilder.CreateCylinder('palm',{height:.16,diameter:.025,tessellation:7},scene);trunk.position.set(.13+i*.05,.12,-.11);trunk.material=mat('trunk','#6B4B32');trunk.parent=root;const leaves=BABYLON.MeshBuilder.CreateSphere('leaves',{diameter:.09,segments:8},scene);leaves.scaling.y=.5;leaves.scaling.x=1.5;leaves.position.set(.13+i*.05,.22,-.11);leaves.material=mat('leaves','#2F8D58');leaves.parent=root}const ad=new GUI.Rectangle();ad.width='210px';ad.height='58px';ad.cornerRadius=10;ad.thickness=4;ad.color=C.ink;ad.background=C.orange;const txt=new GUI.TextBlock();txt.text='SURF CHURCH PORTO\nMATOSINHOS · HOME BASE';txt.color=C.cream;txt.fontFamily='Anton';txt.fontSize=18;ad.addControl(txt);gui.addControl(ad);ad.linkWithMesh(island);ad.linkOffsetY=-70;root.metadata={profile:{id:'hq',name:'Surf Church Porto',city:'Matosinhos',country:'Portugal',lat:41.2269,lon:-8.7053,quote:'Faith. Waves. People.',instagram:'@surfchurchporto'}};return root}
const hq=addHQ();

function addPin(p){const root=new BABYLON.TransformNode('friend-'+p.id,scene);orient(root,latLon(p.lat,p.lon,R+.06));const shadow=BABYLON.MeshBuilder.CreateDisc('pin-shadow',{radius:.09,tessellation:20},scene);shadow.rotation.x=Math.PI/2;shadow.position.y=.01;shadow.material=mat('shadow',C.ink);shadow.parent=root;const ball=BABYLON.MeshBuilder.CreateSphere('friend-pin',{diameter:.13,segments:16},scene);ball.position.y=.18;ball.material=mat('friend-color',p.color||C.yellow);ball.parent=root;const ring=BABYLON.MeshBuilder.CreateTorus('friend-ring',{diameter:.17,thickness:.018,tessellation:20},scene);ring.position.y=.18;ring.material=mat('friend-ring',C.cream);ring.parent=root;root.metadata={profile:p};ball.actionManager=new BABYLON.ActionManager(scene);ball.actionManager.registerAction(new BABYLON.ExecuteCodeAction(BABYLON.ActionManager.OnPickTrigger,()=>showProfile(p)));return root}
let pinNodes=demo.map(addPin);

function renderFriends(list=demo){const el=document.querySelector('#friendList');el.innerHTML='';list.forEach(p=>{const row=document.createElement('div');row.className='friend';row.innerHTML=`<div class="av">${p.first_name[0]}${p.last_name[0]}</div><div class="meta"><b>${p.first_name} ${p.last_name}</b><small>${p.city}, ${p.country}</small></div><i class="dot" style="background:${p.color}"></i>`;row.onclick=()=>showProfile(p);el.appendChild(row)})}
renderFriends();
function showProfile(p){document.querySelector('#profile').classList.add('active');document.querySelector('#avatar').src=p.avatar_url||'';document.querySelector('#pname').textContent=`${p.first_name||p.name} ${p.last_name||''}`;document.querySelector('#pquote').textContent=`“${p.quote||''}”`;document.querySelector('#pinfo').innerHTML=`📍 ${p.city}, ${p.country||''}<br>◎ ${p.instagram||''}<br>🌊 Surf Church community`;}
document.querySelector('#closeProfile').onclick=()=>document.querySelector('#profile').classList.remove('active');
document.querySelector('#search').oninput=e=>{const q=e.target.value.toLowerCase();renderFriends(demo.filter(p=>`${p.first_name} ${p.last_name}`.toLowerCase().includes(q)))};

document.querySelector('#add').onclick=()=>document.querySelector('#modal').classList.add('show');document.querySelector('#closeModal').onclick=()=>document.querySelector('#modal').classList.remove('show');document.querySelector('#cancel').onclick=()=>document.querySelector('#modal').classList.remove('show');
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
document.querySelector('#save').onclick=async()=>{const first=document.querySelector('#first').value.trim(),last=document.querySelector('#last').value.trim(),place=document.querySelector('#place').value.trim();if(!first||!last||!place){toast('Fill in your name and location ✌');return}const p={first_name:first,last_name:last,city:place,country:'',lat:41.2269,lon:-8.7053,quote:document.querySelector('#quote').value.trim()||'Faith. Waves. People.',instagram:document.querySelector('#ig').value.trim()||'',color:C.yellow,avatar_url:`https://i.pravatar.cc/160?u=${encodeURIComponent(first+last)}`};if(supabase){const {data,error}=await supabase.from('profiles').insert({first_name:first,last_name:last,quote:p.quote,instagram:p.instagram,city:place,lat:p.lat,lon:p.lon,avatar_url:p.avatar_url}).select().single();if(error){toast('Could not save your pin');return}p.id=data.id}demo.push(p);pinNodes.push(addPin(p));renderFriends();document.querySelector('#modal').classList.remove('show');showProfile(p);toast('You are on the world! 🌍')};

if(supabase){supabase.from('profiles').select('*').then(({data})=>{if(data?.length){data.forEach(p=>{if(!demo.some(d=>d.id===p.id)){p.color=[C.yellow,C.teal,C.orange,C.blue][demo.length%4];demo.push(p);pinNodes.push(addPin(p))}});renderFriends()}});supabase.channel('profiles-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'profiles'},payload=>{const p=payload.new;if(!demo.some(d=>d.id===p.id)){p.color=C.teal;demo.push(p);pinNodes.push(addPin(p));renderFriends();toast('Someone just joined the world 🌊')}}).subscribe()}

let t=0;engine.runRenderLoop(()=>{t+=.016;world.rotation.y+=.00055;pinNodes.forEach((n,i)=>{const s=1+Math.sin(t*2+i)*.045;n.scaling.set(s,s,s)});hq.scaling.y=1+Math.sin(t*1.7)*.035;scene.render()});window.addEventListener('resize',()=>engine.resize());
